#index:
#    path: /
#    controller: App\Controller\DefaultController::index
catalogue_products:
    path: /catalogue
    controller: App\Controller\CatalogueController::index

cart:
    resource: ../src/Controller/CartController.php
    type: annotation

retirer_produit:
    path: '/panier/retirer/{id}'
    controller: 'App\Controller\PanierController::retirerProduit'
    methods: ['GET']

cart_form:
    path: '/cart/form'
    controller: 'App\Controller\CartController::cartForm'

